server:
  port: 8090
  servlet:
    context-path: /api
    session:
      timeout: PT60M
spring:
  application:
    name: NetDisc
    admin:
      enabled: true
      emails: yangkaihu@yeah.net

  profiles:
    active: local

  mvc:
    favicon:
      enabled: false
    throw-exception-if-no-handler-found: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test??serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HiKariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  mail:
    host: smtp.qq.com
    port: 465
    username: yangkaihu@qq.com
    password: 123456
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory.class: javax.net.ssl.SSLSocketFactory
        debug: true
  redis:
    database: 0
    host: 127.0.0.1
    pool: 6379

    jedis:
      pool:
        max-wait: 1
        max-idle: 10
        min-idle: 0
    timeout: 2000
log:
  root:
    level: debug
logging:
  level:
    root: debug